name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # Runs daily at midnight
  workflow_dispatch:  # You can trigger it manually anytime
  push: {branches: ["master", "main"]}  # Runs when pushing to 'master' or 'main'

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # First metric generation
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Myndaaa
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Singapore
          plugin_introduction: yes
          plugin_introduction_title: yes
      
      # Half-year calendar metric
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
