name: Metrics
on:
  schedule:
    - cron: "0 16 * * *"  # Adjust the cron schedule as needed
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Metrics.LeftPanel
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.leftpanel.svg
          output_action: gist
          committer_gist: ${{ secrets.GIST_ID }}
          token: ${{ secrets.GIST_PAT }}

          config_timezone: UTC
          config_order: base.header, isocalendar, languages, achievements, stars, habits

          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_achievements: yes
          plugin_stars: yes
          plugin_habits: yes

      - name: Metrics.RightPanel
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.rightpanel.svg
          output_action: gist
          committer_gist: ${{ secrets.GIST_ID }}
          token: ${{ secrets.GIST_PAT }}

          base: ""
          config_timezone: UTC
          config_order: steam, anilist, 16personalities
          plugin_steam: yes
          plugin_anilist: yes
          plugin_16personalities: yes
